"""usage ledger and rank tracking

Revision ID: 559e0f49e79c
Revises: a909b71e3abf
Create Date: 2026-09-24 03:09:52.084862
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '559e0f49e79c'
down_revision: str | None = 'a909b71e3abf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index('ix_llm_usage_at', ['at'], unique=False)

    op.create_table('tracked_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('target_url', sa.String(length=1000), nullable=True),
    sa.Column('added_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'keyword', 'country', name='uq_tracked_keyword')
    )
    with op.batch_alter_table('tracked_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_keywords_site_id'), ['site_id'], unique=False)

    op.create_table('rank_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('competitors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['tracked_keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rank_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_rank_snapshots_kw_at', ['keyword_id', 'captured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rank_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_rank_snapshots_kw_at')

    op.drop_table('rank_snapshots')
    with op.batch_alter_table('tracked_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_keywords_site_id'))

    op.drop_table('tracked_keywords')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_usage_at')

    op.drop_table('llm_usage')
    # ### end Alembic commands ###
