"""accounts, credits and billing (multi-tenant SaaS)

Adds customer accounts and users, sessions and one-time auth tokens, the credit ledger and Stripe purchases.
Sites move from a global unique URL to one URL per account; existing sites join an "Operator" workspace.

Revision ID: 912796340fcc
Revises: 559e0f49e79c
Create Date: 2026-09-26 02:55:40.766969
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '912796340fcc'
down_revision: str | None = '559e0f49e79c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('balance_mc', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('notify_secret', sa.Text(), nullable=True),
    sa.Column('credits_warned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_account_id'), ['account_id'], unique=False)

    op.create_table('auth_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount_mc', sa.Integer(), nullable=False),
    sa.Column('balance_mc', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('ref', sa.String(length=200), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reason', 'ref', name='uq_credit_ledger_reason_ref')
    )
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_credit_ledger_account_at', ['account_id', 'created_at'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pack_id', sa.String(length=40), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_account_id'), ['account_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_llm_usage_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key('fk_llm_usage_account_id', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')

    # The old UNIQUE(url) was unnamed; a naming convention lets batch mode find and drop it on every backend
    # (Postgres calls it sites_url_key, which the convention below reproduces).
    with op.batch_alter_table('sites', schema=None, recreate='auto',
                              naming_convention={'uq': '%(table_name)s_%(column_0_name)s_key'}) as batch_op:
        batch_op.drop_constraint('sites_url_key', type_='unique')
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sites_account_id'), ['account_id'], unique=False)
        batch_op.create_unique_constraint('uq_sites_account_url', ['account_id', 'url'])
        batch_op.create_foreign_key('fk_sites_account_id', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    # Existing sites (from the single-workspace version) belong to the operator.
    conn = op.get_bind()
    if conn.execute(sa.text("SELECT COUNT(*) FROM sites")).scalar():
        conn.execute(sa.text("INSERT INTO accounts (name, kind, status, balance_mc, created_at) "
                             "VALUES ('Operator', 'operator', 'active', 0, CURRENT_TIMESTAMP)"))
        op_id = conn.execute(sa.text("SELECT MIN(id) FROM accounts WHERE kind = 'operator'")).scalar()
        conn.execute(sa.text("UPDATE sites SET account_id = :a WHERE account_id IS NULL"), {"a": op_id})
        conn.execute(sa.text("UPDATE llm_usage SET account_id = :a WHERE account_id IS NULL"), {"a": op_id})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrading fails if two accounts registered the same URL; resolve those rows first.
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sites_account_id', type_='foreignkey')
        batch_op.drop_constraint('uq_sites_account_url', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sites_account_id'))
        batch_op.drop_column('account_id')
        batch_op.create_unique_constraint('sites_url_key', ['url'])

    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_llm_usage_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_llm_usage_account_id'))
        batch_op.drop_column('account_id')

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_account_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_credit_ledger_account_at')

    op.drop_table('credit_ledger')
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))

    op.drop_table('auth_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_account_id'))

    op.drop_table('users')
    op.drop_table('accounts')
    # ### end Alembic commands ###
